# Generated by Django 4.1.4 on 2023-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
