# Generated by Django 4.1.4 on 2023-05-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_membershiptype_code_name_and_more'),
        ('account', '0004_customuser_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='root.membershiptype'),
        ),
    ]
