# Generated by Django 4.1.4 on 2023-06-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_shippingaddress_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('is_shipping_free', models.BooleanField(default=False)),
                ('discount_shipping_apply', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.membershiptype'),
        ),
    ]
