# Generated by Django 4.1.4 on 2023-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_membershiptype_delete_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='membership',
        ),
    ]
