# Generated by Django 4.1.4 on 2023-06-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customuser_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.membershiptype'),
        ),
    ]
