# Generated by Django 4.1.4 on 2023-06-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='c_id',
        ),
    ]
