# Generated by Django 4.1.4 on 2023-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_blog_contactus_excelfileupload_globalsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='long_contents',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
