# Generated by Django 4.1.4 on 2023-01-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_products_long_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='most_ordered',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='most_viewed',
            field=models.BigIntegerField(null=True),
        ),
    ]
