# Generated by Django 4.1.4 on 2023-01-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_products_most_ordered_products_most_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_title',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
