# Generated by Django 4.1.4 on 2023-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_alter_globalsettings_site_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=255),
        ),
    ]
