# Generated by Django 4.1.4 on 2023-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='star',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=50),
        ),
    ]
