# Generated by Django 4.1.4 on 2023-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_products_image5_products_image6_products_image7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='Image10',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image11',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image12',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image13',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image4',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image5',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image6',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image7',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image8',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='Image9',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
    ]
