# Generated by Django 4.1.4 on 2023-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_globalsettings_image10_globalsettings_image11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
