# Generated by Django 4.1.4 on 2023-04-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcat', to='root.navigation'),
        ),
    ]
