# Generated by Django 4.1.4 on 2023-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_membershiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
