# Generated by Django 4.1.4 on 2023-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_alter_membershiptype_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='code_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='b2b_membership_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='free_membership_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='platinum_membership_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
