# Generated by Django 4.1.4 on 2023-06-10 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_membershiptype_delete_shippingaddress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0026_remove_products_link_remove_products_most_ordered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MemberShipType',
        ),
        migrations.RemoveField(
            model_name='order',
            name='get_shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_detail',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shipping',
            name='address_1',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='address_2',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='company_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='root.order'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='postcode',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shpping_address',
            field=models.CharField(max_length=2055, null=True),
        ),
    ]
