# Generated by Django 4.1.4 on 2023-06-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_shippingaddress_delete_membershiptype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
