# Generated by Django 4.1.4 on 2023-06-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_remove_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
