# Generated by Django 4.1.4 on 2023-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
