# Generated by Django 4.1.4 on 2023-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='b2b_membership_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='free_membership_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='user/order'),
        ),
        migrations.AddField(
            model_name='order',
            name='platinum_membership_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
