# Generated by Django 4.1.4 on 2023-06-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_remove_order_email_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
