# Generated by Django 4.1.4 on 2023-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.CharField(max_length=121, null=True),
        ),
    ]
